### PR TITLE
Modified game.py and main.py

### PR DESCRIPTION
**Pull request by Riccardo06452**
Changed the game.py to make it able to randomly pick between backgrounds. Using global variables to store a list of images to be picked in order. Currently doesn't handle the event in which we end the list of images. Imported the function play and used it in main.py

### CODE REVIEW

**Comment by Riccardo06452** [comment]
ok i think this conflicts with the modified main created by ankith
wait i will start a new branch from main and fix the main with play usage

**Comment by AnkithAbhayan** [comment]
yeah I've just made 2 changes 1 minute ago. sorry for the inconvenience

**Comment by Riccardo06452** [comment]
No problem same as i did. Now conflicts should be resolved

**Review by AnkithAbhayan — COMMENTED** [review]
this seems legit.

**Pull request merged**
